### ISSUE TITLE
Katkıda Bulunmak İstiyorum

### ISSUE THREAD

**Issue by mertbingol0** [MustafaBilgici/SucoshScanny#1]
Merhaba, projeye katkıda bulunabileceğim, yapabileceğim bir şey var mı? Kendimi DevSec alanında geliştirmeye çalışıyorum ve böyle bir projede çalışıyor olmanın bana ve projeye oldukça katkısı olacağını düşünüyorum. İyi çalışmalar.

**Comment by MustafaBilgici** [comment]
Selamlar Mert,
Tabi projeye katkıda bulunmanı çok isteriz, projeyi incelersen şu an için farklı dillerde detection yöntemleri geliştiriyoruz. Aynı zamanda bunu sonraki aşamada AST gibi modüllerle input takibini kullanarak geliştireceğiz. Çoğu dilde şu anlık sadece modüller yazıldı ancak ana dosyaya işlenmedi(Python hariç) istersen projeyi inceleyip dosya tarama yöntemlerine göre ana dosyada çağırmak için kullanabilirsin o kısma bizde daha geçmedik örnek olarak php içinde lif var ama ana dosyada eklemedik daha onu ya da kendi regex patternlerin ile detection yöntemlerini kendine göre geliştirebilir ya da eksik gördüğün yerleri ekleyebilirsin. Şimdiden katkıların için teşekkürler

**Comment by mertbingol0** [comment]
Tamamdir kurcaliyor olacagim. Rica ederim 🤗

**Comment by MustafaBilgici** [comment]
Contributed issue closed
